### ISSUE TITLE
launch_waveform is not working on emulation

### ISSUE THREAD

**Issue by saitej25** [Xilinx/Vitis_Accel_Examples#10]
In Vitis 2020, ran rtl_kernel /rtl_vadd. 
Created an xrt.ini 
[Debug]
profile=true
launch_waveform=batch
[Runtime]
exclusive_cu_context=true

Test:
make check DEVICE=xilinx_u200_qdma_201920_1 TARGET=hw_emu

Issue: There is no waveform coming up nor there is full wdb database.

**Comment by vishnuchebrolu** [comment]
Hi @saitej25,
Can you refer the following debug_profile design where launch_waveform is used in xrt.ini.
https://github.com/Xilinx/Vitis_Accel_Examples/tree/master/host/debug_profile

Please refer the details.md file of debug_profile regarding the usage launch_waveform field.
https://github.com/Xilinx/Vitis_Accel_Examples/blob/master/host/debug_profile/details.md

Thanks,
Vishnu
