### ISSUE TITLE
multiple different kernels running on the Alevo card

### ISSUE THREAD

**Issue by good-for-nothing-man** [Xilinx/Vitis_Accel_Examples#28]
excuse me, has anyone done a similar project using vitis ?
i want to make an application project about muti_different kernels on the Alevo card. 
i hve tried to make it.  it didn't show some errors about src. However, it failed to build Emulation-SW.
i don't know how to deal with it. 
do you have some demo about this? thanks a lot.

**Comment by vishnuchebrolu** [comment]
Hi, 
you can use the following designs as reference where multiple kernels are running.

1. concurrent_kernel_execution
https://github.com/Xilinx/Vitis_Accel_Examples/tree/master/host/concurrent_kernel_execution

2. kernel_swap
https://github.com/Xilinx/Vitis_Accel_Examples/tree/master/sys_opt/kernel_swap

Thanks,
Vishnu
