### ISSUE TITLE
Problem about Use Vitis IDE to build Kmeans demo

### ISSUE THREAD

**Issue by pyhundan** [Xilinx/Vitis_Accel_Examples#38]
Hello,

How to reproduce:
I took the code from the latest branch and compiled it with a 2020.2 Vitis IDE.

The problem was observed xilinx_u200_xdma_201830_2 platform, and with XRT 2020.2.
The Host system was Ubuntu 16.04. The Vitis IDE's version is v2020.2.0(64bit).

Error:
I create a new application project that uses the Kmeans sample code in the Vitis_Accel_Examples. An error occurred when I tried to compile it using Emulation_sw. I don't do anything to change the code.

The problems show:
```
Errors(2 items)
make:***[package]Error1`
make:***no rule to make target 'krnl_kmeans.cfg', needed by 'krnl_kmeans.xclbin'. Stop`
```

How could I fix it and compile it successfully?

Thank,
Hundan

**Comment by heeran-xilinx** [comment]
Similar query is there in Xilinx Forum, so closing this issue here. 
https://forums.xilinx.com/t5/Vitis-Acceleration-SDAccel-SDSoC/Problem-about-Use-Vitis-IDE-to-build-Kmeans-demo/td-p/1241263
