### ISSUE TITLE
Example host/host_memory_simple (hw_emu) is not compiling

### ISSUE THREAD

**Issue by StefanThorlacius** [Xilinx/Vitis_Accel_Examples#55]
Hi

Is the following error due to installation problem or the example itself, it is example host/host_memory_simple?
It compiles for sw_emu but not hw_emu.

it says "platforminfo <platform.xpfm path> for sptag information" but there is no information about sptag

I am using all the latest stuff from Xilinx, Xilinx Unified Installer 2021.2 including the patch released 6 January.

$ uname -rs
Linux 5.4.0-21-generic

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

HW: U50

----- Start: examples of working built ------
hello_world
make run TARGET=sw_emu PLATFORM=xilinx_u50_gen3x16_xdma_201920_3
TEST PASSED
make run TARGET=hw_emu PLATFORM=xilinx_u50_gen3x16_xdma_201920_3
TEST PASSED
make run TARGET=hw PLATFORM=xilinx_u50_gen3x16_xdma_201920_3
TEST PASSED

----- End: examples of working built ------

host/host_memory_simple
make run TARGET=sw_emu PLATFORM=xilinx_u50_gen3x16_xdma_201920_3
TEST PASSED

make run TARGET=hw_emu PLATFORM=xilinx_u50_gen3x16_xdma_201920_3

INFO: [CFGEN 83-0] Kernel Specs: 
INFO: [CFGEN 83-0]   kernel: krnl_vadd, num: 1  {krnl_vadd_1}
INFO: [CFGEN 83-0] Port Specs: 
INFO: [CFGEN 83-0]   kernel: krnl_vadd_1, k_port: m_axi_gmem, sptag: HOST[0]
ERROR: [CFGEN 83-2287] --sp tag applied with an invalid sp tag: HOST[0]
ERROR: [CFGEN 83-2297] Please consult platforminfo <platform.xpfm path> for sptag information
ERROR: [CFGEN 83-2298] Exiting due to previous error
ERROR: [SYSTEM_LINK 82-36] [16:20:26] cfgen failed
Time (s): cpu = 00:00:02 ; elapsed = 00:00:02 . Memory (MB): peak = 2169.344 ; gain = 0.000 ; free physical = 52644 ; free virtual = 94874
ERROR: [SYSTEM_LINK 82-62] Error generating design file for /home/zzzzzz/.Xilinx/Vitis/2021.2/vitis_examples/Vitis_Accel_Examples/host/host_memory_simple/_x.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/link/sys_link/cfgraph/cfgen_cfgraph.xml, command: /tools/Xilinx/Vitis/2021.2/bin/cfgen  -sp krnl_vadd_1.m_axi_gmem:HOST[0] -dmclkid 0 -r /home/zzzzzz/.Xilinx/Vitis/2021.2/vitis_examples/Vitis_Accel_Examples/host/host_memory_simple/_x.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/link/sys_link/_sysl/.cdb/xd_ip_db.xml -o /home/zzzzzz/.Xilinx/Vitis/2021.2/vitis_examples/Vitis_Accel_Examples/host/host_memory_simple/_x.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/link/sys_link/cfgraph/cfgen_cfgraph.xml
ERROR: [SYSTEM_LINK 82-96] Error applying explicit connections to the system connectivity graph
ERROR: [SYSTEM_LINK 82-79] Unable to create system connectivity graph
INFO: [v++ 60-1442] [16:20:26] Run run_link: Step system_link: Failed
Time (s): cpu = 00:00:07 ; elapsed = 00:00:06 . Memory (MB): peak = 2063.574 ; gain = 0.000 ; free physical = 52681 ; free virtual = 94912
ERROR: [v++ 60-661] v++ link run 'run_link' failed
ERROR: [v++ 60-626] Kernel link failed to complete
ERROR: [v++ 60-703] Failed to finish linking
INFO: [v++ 60-1653] Closing dispatch client.
make: *** [Makefile:132: build_dir.hw_emu.xilinx_u50_gen3x16_xdma_201920_3/krnl_vadd.xclbin] Error 1

**Comment by vishnuchebrolu** [comment]
@StefanThorlacius  the platform that you are targeting (xilinx_u50_gen3x16_xdma_201920_3) does not have "HOST" memory. It had the following memory resources : 
HBM : 0 - 31
PLRAM : 0 - 3

Please pick the platform that had HOST memory and try re-running the design.

Thanks,
Vishnu

**Comment by StefanThorlacius** [comment]
Thanks
