### ISSUE TITLE
aie_adder: misleading readme, hardcoded xclbin name

### ISSUE THREAD

**Issue by ksstms** [Xilinx/Vitis_Accel_Examples#59]
The [aie_adder's readme](https://github.com/Xilinx/Vitis_Accel_Examples/blob/master/aie_kernels/aie_adder/README.rst#command-line-arguments) says that it takes the `xclbin` filename as argument:
```
./aie_adder <krnl_adder XCLBIN>
```

Meanwhile the [host code](https://github.com/Xilinx/Vitis_Accel_Examples/blob/master/aie_kernels/aie_adder/sw/host.cpp#L52-L60) completely ignores the arguments, and `krnl_adder.xclbin` is hardcoded:
```cpp
int main(int argc, char** argv) {
    //////////////////////////////////////////
    // Open xclbin
    //////////////////////////////////////////
    auto dhdl = xrtDeviceOpen(0); // Open Device the local device
    if (dhdl == nullptr) throw std::runtime_error("No valid device handle found. Make sure using right xclOpen index.");
    auto xclbin = load_xclbin(dhdl, "krnl_adder.xclbin");
    auto top = reinterpret_cast<const axlf*>(xclbin.data());
    adf::registerXRT(dhdl, top->m_header.uuid);
```

**Comment by vishnuchebrolu** [comment]
@ksstms Thanks for reporting on this. We will update the readme file.

Thanks,
Vishnu
