### ISSUE TITLE
Vitis_Accel_Examples/hello_world   example  question

### ISSUE THREAD

**Issue by crizy** [Xilinx/Vitis_Accel_Examples#63]
i run hello_world   example,  HLS generate  vadd.cpp   kernel , i find  TARGET_ADDR   moved 1g with USER_ADDR genarate vadd rtl ip
as follows,

        TARGET_ADDR     = C_TARGET_ADDR & (32'hffffffff << USER_ADDR_ALIGN)

I want to know 1g(32'hffffffff)  how this is set up in hls,thans

**Comment by vishnuchebrolu** [comment]
Hi @crizy ,
I would suggest you to post your query on the Xilinx Forum -
https://support.xilinx.com/s/topic/0TO2E000000YKYAWA4/vitis-acceleration-acceleration?language=en_US

Thanks,
Vishnu

**Comment by heeran-xilinx** [comment]
Closing as requested to file case at Xilinx Forum.
