### ISSUE TITLE
New Makefile structure ignores existing PLATFORM value

### ISSUE THREAD

**Issue by deffel** [Xilinx/Vitis_Accel_Examples#64]
Hey, the new Makefiles coming with this commit:

https://github.com/Xilinx/Vitis_Accel_Examples/commit/87303a38593ed9c51317b033ea7572dee844d134

overwrite the PLATFORM environment variable statically to "xilinx_u250_gen3x16_xdma_3_1_202020_1", see for example

https://github.com/Xilinx/Vitis_Accel_Examples/commit/87303a38593ed9c51317b033ea7572dee844d134#diff-6451b310096fb4ab024f3d7dc6b5ddff7688e0d757561496e6cf3b0fc185e36fR26

This breaks the "out-of-the-box" usage of the examples as it was possible to use before. Could you please set the variable via:

PLATFORM ?= xilinx_u250_gen3x16_xdma_3_1_202020_1

This would only assign the PLATFORM value, if it is not set yet.

Thanks and best regards.

**Comment by vishnuchebrolu** [comment]
@deffel  Thanks for your suggestion. We will update the PLATFORM variable as it makes more sense to assign the value if only not set.

Thanks,
Vishnu

**Comment by vishnuchebrolu** [comment]
Hi @deffel ,
We have updated the designs  to use the following in all makefiles.
PLATFORM ?= xilinx_u250_gen3x16_xdma_3_1_202020_1

**Comment by deffel** [comment]
@vishnuchebrolu tested here, works perfectly. thanks
