### ISSUE TITLE
Is it possible to do software emulation without Xilinx FPGA and run the code on CPU?

### ISSUE THREAD

**Issue by enes1994** [Xilinx/Vitis_Accel_Examples#68]
Hi,

I would like to know if there is a possibility to do software emulation without Xilinx FPGA and run the code on CPU? I am kind of new and searching for some way to do this.

**Comment by mruizglz** [comment]
Yes, you can do it. Use the SW or HW emulation functionality in VITIS.

**Comment by mruizglz** [comment]
Have a look at this: https://xilinx.github.io/xup_compute_acceleration/Vitis_intro-1.html
