### ISSUE TITLE
Cannot decrease the reference clock frequency for u200

### ISSUE THREAD

**Issue by tangyuelm** [Xilinx/Vitis_Accel_Examples#69]
Dear Sir/Madam,

I am using the Vitis 2019.2 tool to implement some code on the U200 board. I found the timing requirement cannot be satisfied using the default 300MHZ frequency so I tried to decrease it but failed. I have attached the .txt version of my Makefile. I have made the following changes:

TARGET := hw
HOST_ARCH := x86
SYSROOT := 
+FREQ := 200000000

.PHONY: build
build: $(BINARY_CONTAINERS)

# Building kernel
$(TEMP_DIR)/$(KERNEL).xo: src/$(KERNEL).cpp
	mkdir -p $(TEMP_DIR)
	$(VPP) $(CLFLAGS) --temp_dir $(TEMP_DIR) -c -k $(KERNEL) --kernel_frequency 200 -o'$@' '$<'
$(BUILD_DIR)/$(KERNEL).xclbin: $(BINARY_CONTAINER_kernel_OBJS)
	mkdir -p $(BUILD_DIR)
	$(VPP) $(CLFLAGS) --temp_dir $(BUILD_DIR) -l --kernel_frequency 200 -o'$@' $(+)

# Building Host
$(EXECUTABLE): check-xrt $(HOST_SRCS) $(HOST_HDRS)
	$(CXX) $(CXXFLAGS) $(HOST_SRCS) $(HOST_HDRS) -o '$@' $(LDFLAGS)

I also tried to the following command to generate the botstream
faketime 'last year' make all TARGET=hw DEVICE=xilinx_u200_xdma_201830_2 FREQ=200000000 -B
[Makefile.txt](https://github.com/Xilinx/Vitis_Accel_Examples/files/9107210/Makefile.txt)

The above attempts can only change the HLS synthesis results, but the timing results in the xilinx_u200_xdma_201830_2_bb_locked_timing_summary_routed.rpt file still remains unchanged.

Can anyone help me to reduce the PL frequency?

**Comment by heeran-xilinx** [comment]
Can you please post your query on the Xilinx Forum?
https://support.xilinx.com/s/topic/0TO2E000000YKYAWA4/vitis-acceleration-acceleration?language=en_US
