### ISSUE TITLE
AIE support on VCK5000

### ISSUE THREAD

**Issue by JuanEsco063** [Xilinx/Vitis_Accel_Examples#74]
Can you provide more details on the current status of supporting development of applications using the AIE on the VCK5000? 

Currently it is on the unsupported device list of the AIE example. Is this due to a driver/software issue?

Thanks in advance

**Comment by vishnuchebrolu** [comment]
Hi @JuanEsco063 ,

Can you please post your query to forum
https://support.xilinx.com/s/topic/0TO2E000000YKYAWA4/vitis-acceleration-acceleration?language=en_US

Thanks,
Vishnu
