### ISSUE TITLE
Segmentation fault (core dumped) after programming .xclbin file to U50 board

### ISSUE THREAD

**Issue by IskandarZhang** [Xilinx/Vitis_Accel_Examples#76]
In order to test the limit throughput of hmss ip, I modified `hbm_large_buffer` example. I created 6 `inputs` in codes in `src`  according to the method of creating `input` and `output` as the example shows, and made corresponding modifications in the `.cfg` file also. In this way, the `xclbin` file was successfully generated, but after programming to the board this error occured.

My XRT version is 2.11.634 and version of Vitis is 2021.1

Thanks in advance.

**Comment by heeran-xilinx** [comment]
Please post such query to following Xilinx Forum:
https://support.xilinx.com/s/topic/0TO2E000000YKYAWA4/vitis-acceleration-acceleration?language=en_US
